package com.example.shopinglist.data

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import com.example.shopinglist.domain.shopItem.ShopItem
import com.example.shopinglist.domain.shopItem.ShopListRepository
import kotlin.random.Random

object ShopLIstRepositoryImpl : ShopListRepository {

    private val shopListItemLD = MutableLiveData<List<ShopItem>>()
    private val shopList = sortedSetOf<ShopItem>(compareBy { it.id })

    private var autoGeneratedId = 0

    init {

        for (i in 0 until 100) {
            val item = ShopItem(name = "Name - $i", count = i, isActivated = Random.nextBoolean())
            insertShopItem(item)
        }
    }

    override fun insertShopItem(item: ShopItem) {
        if (item.id == ShopItem.UNDEFINED_ID) {
            item.id = autoGeneratedId++
        }
        shopList.add(item)
        updateLiveData()
    }

    override fun getShopList(): LiveData<List<ShopItem>> {
        return shopListItemLD
    }

    override fun updateShopItem(item: ShopItem) {
        val oldItem = getShopItemById(item.id)
        shopList.remove(oldItem)
        insertShopItem(item)
        updateLiveData()
    }

    override fun getShopItemById(idItem: Int): ShopItem {
        return shopList.find { it.id == idItem }
            ?: throw RuntimeException("Item with id: $idItem not found")
    }

    override fun deleteShopItem(item: ShopItem) {
        shopList.remove(item)
        updateLiveData()
    }

    private fun updateLiveData() {
        shopListItemLD.value = shopList.toList()
    }
}